version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates for Maven dependencies
    # we use renovate-bot as well as shared-dependencies BOM to update maven dependencies.
    ignore: "*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates for pip dependencies
    # If a security vulnerability comes in, we will be notified about 
    # it via template in the synthtool repository.
    ignore: "*"
