rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
      - 'Kokoro - Test: Java GraalVM Native Image'
      - 'Kokoro - Test: Java 17 GraalVM Native Image'
  - pattern: 1.127.12-sp
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (7)
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
  - pattern: java7
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (7)
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
  - pattern: 2.3.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
  - pattern: 2.10.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
  - pattern: 2.19.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
      - 'Kokoro - Test: Java GraalVM Native Image'
      - 'Kokoro - Test: Java 17 GraalVM Native Image'
permissionRules:
  - team: api-bigquery
    permission: admin
  - team: yoshi-java
    permission: push
  - team: yoshi-admins
    permission: admin
  - team: yoshi-java-admins
    permission: admin
