rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
      - 'Kokoro - Test: Java GraalVM Native Image'
      - 'Kokoro - Test: Java 17 GraalVM Native Image'
  - pattern: 1.106.5-sp
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
  - pattern: java7
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (7)
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
  - pattern: 2.1.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
  - pattern: 2.2.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
  - pattern: 2.12.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
      - 'Kokoro - Test: Java GraalVM Native Image'
      - 'Kokoro - Test: Java 17 GraalVM Native Image'
  - pattern: multi-db
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
      - 'Kokoro - Test: Java GraalVM Native Image'
      - 'Kokoro - Test: Java 17 GraalVM Native Image'
permissionRules:
  - team: yoshi-admins
    permission: admin
  - team: yoshi-java-admins
    permission: admin
  - team: yoshi-java
    permission: push
