rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - units (8)
      - units (11)
      - units (17)
      - cla/google
      - enforcer
      - lint
      - 'Kokoro - Test: Integration'
      - 'Kokoro - Test: GraalVM Native Image A'
      - 'Kokoro - Test: GraalVM Native Image B'
      - header-check
      - library_generation
  - pattern: 1.0.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - units (8)
      - units (11)
      - units (17)
      - cla/google
      - enforcer
      - lint
      - 'Kokoro - Test: Integration'
  - pattern: 1.13.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - units (8)
      - units (11)
      - units (17)
      - cla/google
      - enforcer
      - lint
      - 'Kokoro - Test: Integration'
  - pattern: 1.25.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - units (8)
      - units (11)
      - units (17)
      - cla/google
      - enforcer
      - lint
      - OwlBot Post Processor
      - 'Kokoro - Test: Integration'
      - 'Kokoro - Test: GraalVM Native Image A'
      - 'Kokoro - Test: GraalVM Native Image B'
      - header-check
permissionRules:
  - team: yoshi-admins
    permission: admin
  - team: yoshi-java-admins
    permission: admin
  - team: yoshi-java
    permission: push
