language: java
dist: trusty
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: linux
    jdk: openjdk7
    #  - os: osx
    #env: JAVA_HOME=$(/usr/libexec/java_home)
before_install:
- mvn clean
- travis_retry git clone -b travis `git config --get remote.origin.url` target/travis
- cp target/travis/settings.xml ~/.m2/settings.xml
- cp target/travis/logging.properties logging.properties
install: mvn install --quiet -Djava.util.logging.config.file=logging.properties -DskipTests=true
  -Dgpg.skip=true
script:
- travis_wait 60 utilities/verify.sh
after_success:
- utilities/after_success.sh
env:
  global:
  - secure: IvdIao/ZBKZ7KcMdbnbpPH5dyujVnr1PAlE9hV+Nu5YujloIDUqTFpSFXB+wnp0CLMlW2kBR6YBhh71mp5M2XSqf+PtWB3b+ts7oz1vwhfUI857P5lMBHapekkNJk874sMjPdAUIprRnRBmVBfZVLMrSDE7LKqnuHXZjSkDGFYk=
  - secure: XCtBrBNHGL+c55erAzMGgfCbS7dXSAFrMqIQCiPD6ib9rde3G8aDMvsseY7jSO2ygspB4ubVr+WqNkC5yHMcNUQvkX/auNpSkJbzBFG/2lhC9NBvBAiFJZn5jmcVnQ19vgO2Zjd37B1NrIwT7sW49eVeG0zn/A+qRxWeagPy3SQ=
  - secure: YBbdzseg5yDFpQIiMoc3P2BTmqef4o+KAvrLMEbobXjIkiglUQ7UHCoRWClX74fTKAwuC7JvK7o5xJGLnaY43jJADXrGtE8/d44HNJaieE67mNosDYtOiA0iI2uIRFCAnXJCZ8f/iHx2xVMHMNWlwyoil4IUcjj+D7FRcsT5alE=
  - secure: Od7BwllgFXVfzFe8ooTNm05TR+Xd5QjHW0oqhU8vclaQs2oX4e0eNIsebXQfLi3xDgd1pz5uUQC/Z4S0NqACwyUuUvPdGYYmRPTR7Dh8HgGJ4ojSdN3RwaHsxUqG7Ajts9rIHOtRpY28xOChVRNX0Z7eAPlvxYU4Ed2ZEo356r0=
  - secure: ROxa8HHuba+Dfixljq6poW1+Uwv8EaZUtTTTB7KEtAHJRN8rwoNS4TC0U0PEHcYAL+ivxP3zIfWOCoWreJGoa+V8y9BtLSuamUj/SSsuoHRdJjq5BmcHI/77P11HAzCH6Ul/GxsRB52/IRHwJyfKkh8XUMVSsCl7AG4CKUgt63Y=
  - secure: MKZ3y6IYp3Z67T+BO4Brw+my8sRMSMdWWgvUcyBpwQZ64w7ccHJCce4W8WHCPNko/eczHHCJELPG28VNyPTWIV/Jt2ZJ6L9qLCjsQpDPOdJdDaAKc9Df4sm8fB0FBiPVDwMYPQF1/Sy2gK7FZf0YR3LOeoyzswRgmj5bQMdVEeU=
  - secure: QlUWsbFDH89PrCC9WZxjON4cylTKBUg7zoYoQiTw90+FCvokaas4PaXDPVmzY1AxPv/ZQWSrcMgLhz43GASD8Ty96bOIKBB8tO6k0FVzff9r9bpiHssNiW0kDp657BFON4UWG75T6wJxKp4jsttvLfhBFMBLKg+fpYlKnaOPqDc=
  - secure: hnS0gmrb/u/Cg2ldirv+DOSVtVD2UJCEV+iIpvEqKgzvJv4arYC3OKO+dpztk+sKaiXNSPr8BvHyRNxPH1hJUthovp3MyZNqhSz55JL/yjBSCzYrKHZpjxKq6HpIjr5xxFqyqj6TXqalVD6+UutlfytagoX0YBtEH52zcVzkC8M=
