gapic_generator_version: 2.66.0
googleapis_commitish: 2ac88973cbafba24e4fb6f31038e0c76174ae704
libraries_bom_version: 26.74.0
libraries:
  - api_shortname: logging
    name_pretty: Cloud Logging
    product_documentation: https://cloud.google.com/logging/docs
    client_documentation: https://cloud.google.com/java/docs/reference/google-cloud-logging/latest/history
    issue_tracker: https://issuetracker.google.com/savedsearches/559764
    release_level: stable
    language: java
    repo: googleapis/java-logging
    repo_short: java-logging
    distribution_name: com.google.cloud:google-cloud-logging
    api_id: logging.googleapis.com
    transport: grpc
    library_type: GAPIC_COMBO
    api_description: allows you to store, search, analyze, monitor, and alert on log data and events from Google Cloud and Amazon Web Services. Using the BindPlane service, you can also collect this data from over 150 common application components, on-premises systems, and hybrid cloud systems. BindPlane is included with your Google Cloud project at no additional cost.
    codeowner_team: '@googleapis/cloud-sdk-java-team'
    recommended_package: com.google.cloud.logging
    GAPICs:
      - proto_path: google/logging/v2
