gapic_generator_version: 2.45.0
googleapis_commitish: a18d9b2c3563527b26c4b713469e795b92795271
libraries_bom_version: 26.47.0

# the libraries are ordered with respect to library name, which is
# java-{library.library_name} or java-{library.api-shortname} when
# library.library_name is not defined.
libraries:
- api_shortname: advisorynotifications
  name_pretty: Advisory Notifications API
  product_documentation: https://cloud.google.com/advisory-notifications/
  api_description: An API for accessing Advisory Notifications in Google Cloud.
  release_level: stable
  GAPICs:
  - proto_path: google/cloud/advisorynotifications/v1

- api_shortname: aiplatform
  name_pretty: Vertex AI
  product_documentation: https://cloud.google.com/vertex-ai/docs
  api_description: is an integrated suite of machine learning tools and services for
    building and using ML models with AutoML or custom code. It offers both novices
    and experts the best workbench for the entire machine learning development lifecycle.
  release_level: stable
  rest_documentation: https://cloud.google.com/vertex-ai/docs/reference/rest
  rpc_documentation: https://cloud.google.com/vertex-ai/docs/reference/rpc
  GAPICs:
  - proto_path: google/cloud/aiplatform/v1
  - proto_path: google/cloud/aiplatform/v1beta1