# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Github action job to test core java library features on
# downstream client libraries before they are released.
on:
  pull_request:
    types: [ labeled ]
    branches:
    - main
name: downstream
jobs:
  dependencies:
    if: ${{ github.event.label.name == 'downstream-check:run' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17]
        repo:
        # This list needs to be updated manually until an automated solution is in place.
        - accessapproval
        - accesscontextmanager
        - aiplatform
        - analytics-admin
        - analytics-data
        - api-gateway
        - apigee-connect
        - appengine-admin
        - area120-tables
        - artifact-registry
        - asset
        - assured-workloads
        - automl
        - bigquery
        - bigqueryconnection
        - bigquerydatatransfer
        - bigquerymigration
        - bigqueryreservation
        - bigtable
        - billing
        - billingbudgets
        - binary-authorization
        - channel
        - cloudbuild
        - compute
        - contact-center-insights
        - container
        - containeranalysis
        - data-fusion
        - datacatalog
        - dataflow
        - datalabeling
        - dataproc
        - dataproc-metastore
        - datastore
        - datastream
        - debugger-client
        - deploy
        - dialogflow
        - dialogflow-cx
        - dlp
        - dms
        - dns
        - document-ai
        - domains
        - errorreporting
        - essential-contacts
        - eventarc
        - filestore
        - firestore
        - functions
        - game-servers
        - gke-connect-gateway
        - gkehub
        - gsuite-addons
        - iam-admin
        - iamcredentials
        - iot
        - kms
        - language
        - life-sciences
        - logging
        - logging-logback
        - managed-identities
        - mediatranslation
        - memcache
        - monitoring
        - monitoring-dashboards
        - network-management
        - network-security
        - networkconnectivity
        - notebooks
        - orchestration-airflow
        - orgpolicy
        - os-config
        - os-login
        - phishingprotection
        - policy-troubleshooter
        - private-catalog
        - profiler
        - pubsublite
        - recaptchaenterprise
        - recommendations-ai
        - recommender
        - redis
        - resource-settings
        - resourcemanager
        - retail
        - scheduler
        - secretmanager
        - security-private-ca
        - securitycenter
        - securitycenter-settings
        - service-control
        - service-management
        - service-usage
        - servicedirectory
        - shell
        - spanner
        - spanner-jdbc
        - speech
        - storage
        - storage-nio
        - storage-transfer
        - talent
        - tasks
        - texttospeech
        - tpu
        - trace
        - translate
        - video-intelligence
        - video-transcoder
        - vision
        - vpcaccess
        - webrisk
        - websecurityscanner
        - workflow-executions
        - workflows
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        java-version: ${{matrix.java}}
    - run: java -version
    - run: sudo apt-get install libxml2-utils
    - run: .kokoro/downstream-client-library-check.sh google-cloud-core-bom ${{matrix.repo}}
