
# Whether or not rebase-merging is enabled on this repository.
# Defaults to `true`
rebaseMergeAllowed: false

# Whether or not squash-merging is enabled on this repository.
# Defaults to `true`
squashMergeAllowed: true

# Whether or not PRs are merged with a merge commit on this repository.
# Defaults to `false`
mergeCommitAllowed: false

# Rules for master branch protection
branchProtectionRules:
# Identifies the protection rule pattern. Name of the branch to be protected.
# Defaults to `master`
- pattern: master
  # Can admins overwrite branch protection.
  # Defaults to `true`
  isAdminEnforced: true
  # Number of approving reviews required to update matching branches.
  # Defaults to `1`
  requiredApprovingReviewCount: 1
  # Are reviews from code owners required to update matching branches.
  # Defaults to `false`
  requiresCodeOwnerReviews: true
  # Require up to date branches
  requiresStrictStatusChecks: false
  # List of required status check contexts that must pass for commits to be accepted to matching branches.
  requiredStatusCheckContexts:
  - "dependencies (8)"
  - "dependencies (11)"
  - "linkage-monitor"
  - "lint"
  - "clirr"
  - "units (7)"
  - "units (8)"
  - "units (11)"
  - "Kokoro - Test: Integration"
  - "cla/google"
  - "OwlBot Post Processor"
# List of explicit permissions to add (additive only)
permissionRules:
- team: yoshi-admins
  permission: admin
- team: yoshi-java-admins
  permission: admin
- team: yoshi-java
  permission: push
