on:
  pull_request:
    types:
      - synchronize
name: Module specific CHANGELOG.md generation
jobs:
  changelog_generation:
    runs-on: ubuntu-latest
    if: |
      github.event.sender.login == 'release-please-bot' && github.event.pull_request.head.ref == 'release-please--branches--main' &&
      contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
    steps:
      - run: echo "running the changelog generation script..."
