# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# GitHub action job to test core java library features on
# downstream client libraries before they are released.
name: Hermetic library generation upon generation config change through pull requests
on:
  pull_request:

env:
  REPO_FULL_NAME: ${{ github.event.pull_request.head.repo.full_name }}
  GITHUB_REPOSITORY: ${{ github.repository }}
jobs:
  library_generation:
    runs-on: ubuntu-latest
    steps:
    - name: Determine whether the pull request comes from a fork
      run: |
        if [[ "${GITHUB_REPOSITORY}" != "${REPO_FULL_NAME}" ]]; then
          echo "This PR comes from a fork. Skip library generation."
          echo "SHOULD_RUN=false" >> $GITHUB_ENV
        else
          echo "SHOULD_RUN=true" >> $GITHUB_ENV
        fi
    - uses: actions/checkout@v4
      if: env.SHOULD_RUN == 'true'
      with:
        fetch-depth: 0
        token: ${{ secrets.CLOUD_JAVA_BOT_TOKEN }}
    - uses: googleapis/sdk-platform-java/.github/scripts@v2.61.0
      if: env.SHOULD_RUN == 'true'
      with:
        base_ref: ${{ github.base_ref }}
        head_ref: ${{ github.head_ref }}
        token: ${{ secrets.CLOUD_JAVA_BOT_TOKEN }}
