name: Monorepo Script CI
on:
  schedule:
    - cron: '0 1 * * *' # nightly at 1 am UTC
  push:
    branches: [ monorepo_script ]
  pull_request:
    branches: [ monorepo_script ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Monorepo
        run: ./bootstrap.sh
        env:
          USERNAME: ${{ github.actor }}
      - name: Compile
        working-directory: monorepo/google-cloud-java
        run: mvn compile -T C1 -B
      - name: Unit Tests
        working-directory: monorepo/google-cloud-java
        run: mvn test -T C1 -B
      - name: Push monorepo to branch
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd monorepo/google-cloud-java
          git remote add monorepo https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
          git push -f monorepo main:monorepo_script_output
      - name: Push diff to branch
#        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd monorepo/diff
          git remote add monorepo https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
          git push -f monorepo main:split_vs_mono_diff_output          

  build-3repos:
    runs-on: ubuntu-latest
    name: Running bootstrap.sh with only 3 selected repositories
    steps:
    - uses: actions/checkout@v3
    - name: Truncate repos.txt for 3 repositories
      run: |
        cat << EOL > repos.txt
        java-accessapproval
        java-dns
        java-resourcemanager
        EOL
    - name: Monorepo
      run: ./bootstrap.sh
      shell: bash
      env:
        USERNAME: ${{ github.actor }}
    - name: Compile
      working-directory: monorepo/google-cloud-java
      run: mvn compile -T C1 -B
    - name: Unit Tests
      working-directory: monorepo/google-cloud-java
      run: mvn test -T C1 -B
