on:
  pull_request:
name: Unmanaged dependency check
jobs:
  unmanaged_dependency_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Install modules
      shell: bash
      run: .kokoro/build.sh
    - name: Unmanaged dependency check
      uses: googleapis/sdk-platform-java/java-shared-dependencies/unmanaged-dependency-check@unmanaged-dependencies-check-latest
      with:
        bom-path: google-cloud-datastore-bom/pom.xml
