on:
  pull_request:
name: Unmanaged dependency check
jobs:
  unmanaged_dependency_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Install modules
        shell: bash
        run: |
          # No argument to build.sh installs the modules in local Maven
          # repository
          .kokoro/build.sh
      - name: Unmanaged dependency check
        uses: googleapis/sdk-platform-java/java-shared-dependencies/unmanaged-dependency-check@google-cloud-shared-dependencies/v3.30.1
        with:
          bom-path: google-cloud-bigquerystorage-bom/pom.xml
