on:
  pull_request:
name: Unmanaged dependency check
jobs:
  unmanaged_dependency_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - name: Install modules
      shell: bash
      run: .kokoro/build.sh
    - name: Unmanaged dependency check
      uses: googleapis/sdk-platform-java/java-shared-dependencies/unmanaged-dependency-check@google-cloud-shared-dependencies/v3.30.0
      with:
        bom-path: pom.xml
