name: Verify Generation Configuration
on:
  schedule:
  - cron: '0 2 * * *' # nightly at 2 am UTC
  workflow_dispatch:

jobs:
  generate-from-configuration:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: setup docker environment
      shell: bash
      run: |
        # we create a volume pointing to `pwd` (google-cloud-java) that will
        # be referenced by the container and its children
        if [[ $(docker volume inspect repo) != '[]' ]]; then
          docker volume rm repo
        fi
        docker volume create --name "repo" --opt "type=none" --opt "device=$(pwd)" --opt "o=bind"
    - name: generate from configuration
      shell: bash
      run: |
        git config --global user.email "github-workflow@github.com"
        git config --global user.name "Github Workflow"
        docker run --rm \
          -v repo:/workspace \
          -v /tmp:/tmp \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e "RUNNING_IN_DOCKER=true" \
          -e "REPO_BINDING_VOLUME=repo" \
          gcr.io/cloud-devrel-public-resources/java-library-generation:latest \
          python /src/generate_repo.py generate --generation-config-yaml=/workspace/generation_config.yaml --repository-path=/workspace
